version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: marketflow_app
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        networks:
            - marketflow_network
    db:
        image: mysql:latest
        container_name: marketflow_container_db
        restart: unless-stopped
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: marketflow_db
            MYSQL_USER: marketflow_user
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - marketflow_network

volumes:
    db_data:
networks:
    marketflow_network:
        driver: bridge
